descriptors: 
  run: True
  n_jobs: 1
  device: cuda:4
  batch_size: 512

structure_filters: 
  run: True
  sample_size: 10000
  save_dir: /mnt/ligandpro/data/gurevich/medchem_filters
  filename: common_filter
  mode: 'scratch' # options 'scratch' or 'continue'

retrosynthesis: 
  run: False

smina_score: 
  run: False



data:
  pains_file_path: data/wehi_pains.csv
  mcf_file_path: data/mcf.csv

  molecules_to_compare_with_seen: /home/dorochka/projects/testing_benchmark/KRAS_inhibs_seen_1.smi
  molecules_to_compare_with_unseen: /home/dorochka/projects/testing_benchmark/KRAS_inhibs_unseen_1.smi