run: true
n_jobs: -1
batch_size: 1000
filter_data: true

preprocess:
  # MolPrep stage owns molecule standardization. Keep these disabled to avoid
  # double-processing the same transformations. If you disable MolPrep, you can
  # enable these as a fallback (but MolPrep is recommended).
  remove_charges: false
  remove_radicals: false
  remove_stereochemistry: false

borders:
  allowed_chars:
  - C
  - N
  - S
  - O
  - F
  - Cl
  - Br
  - I
  - P
  - H
  n_atoms_min: 10
  n_atoms_max: 100
  n_heavy_atoms_min: 10
  n_heavy_atoms_max: 50
  n_het_atoms_min: 2
  n_het_atoms_max: 15
  n_N_atoms_min: 0
  n_N_atoms_max: 12
  fN_atoms_min: 0
  fN_atoms_max: 0.22

  fNS_atoms_min: 0
  fNS_atoms_max: 0.3
  charged_mol_allowed: true
  filter_charged_mol: false
  molWt_min: 200
  molWt_max: 550
  logP_min: -0.4
  logP_max: 5.6
  clogP_min: 0
  clogP_max: 8

  sw_min: -20
  sw_max: 1
  ring_size_min: 3
  ring_size_max: 12
  n_rings_min: 0
  n_rings_max: 6
  n_aroma_rings_min: 0
  n_aroma_rings_max: 5
  n_fused_aromatic_rings_min: 0
  n_fused_aromatic_rings_max: 2
  n_rigid_bonds_min: 0
  n_rigid_bonds_max: 30
  n_rot_bonds_min: 0
  n_rot_bonds_max: 8
  hbd_min: 0
  hbd_max: 4
  hba_min: 1
  hba_max: 9
  fsp3_min: 0.15
  fsp3_max: 0.8
  mce18_min: 20
  mce18_max: 140
  tpsa_min: 20
  tpsa_max: 140
  qed_min: 0.3
  qed_max: 1
filtered_cols_to_plot:
- chars
- n_atoms
- n_heavy_atoms
- n_het_atoms
- n_N_atoms
- fN_atoms
- fNS_atoms
- charged_mol
- molWt
- logP
- clogP
- sw
- ring_size
- n_rings
- n_aroma_rings
- n_fused_aromatic_rings
- n_rigid_bonds
- n_rot_bonds
- hbd
- hba
- fsp3
- mce18
- tpsa
- qed
discrete_features_to_plot:
- chars
- n_het_atoms
- n_N_atoms
- charged_mol
- ring_size
- n_rings
- n_aroma_rings
- n_fused_aromatic_rings
- n_rigid_bonds
- n_rot_bonds
- hbd
- hba
not_to_smooth_plot_by_sides:
- n_atoms
- n_heavy_atoms
- fN_atoms
- fNS_atoms
- molWt
- fsp3
- tpsa
- qed
renamer:
  chars: Chars in molecules
  n_atoms: Number of Atoms
  n_heavy_atoms: Number of Heavy Atoms
  n_het_atoms: Number of heteroatoms
  n_N_atoms: Number of Nitrogen Atoms
  fN_atoms: Fraction of Nitrogen Atoms
  fNS_atoms: Fraction of Nitrogen and Sulfur Atoms
  charged_mol: Charged Molecule
  molWt: Molecular Weight
  logP: logP
  clogP: clogP
  sw: Water Solubility (Sw)
  ring_size: Size of rings
  n_rings: Number of rings
  n_aroma_rings: Number of aromatic rings
  n_fused_aromatic_rings: Number of fused aromatic rings
  n_rigid_bonds: Number of rigid bonds
  n_rot_bonds: Number of rotatable bonds
  hbd: Hydrogen Bond Donors
  hba: Hydrogen Bond Acceptors
  fsp3: Fraction of SP3
  mce18: MCE-18 Complexity
  tpsa: TPSA
  qed: QED
