run: true
tools: gnina  # Options: gnina, smina, both
receptor_pdb: data/test/7EW9_apo.pdb
auto_run: true
run_in_background: false
per_molecule_docking: true
gnina_per_process_cpu: 8
gnina_parallel_jobs_scale: 2.0
gnina_parallel_jobs_max: 8
ligprep_njobs: auto

smina_config:
  bin: smina
  autobox_ligand: data/test/05C_from_7EW9.sdf
  autobox_add: 4
  cpu: 32
  seed: 42
  exhaustiveness: 8
  num_modes: 1

gnina_config:
  bin: /mnt/ligandpro/soft/docking/gnina/gnina
  autobox_ligand: data/test/05C_from_7EW9.sdf
  autobox_add: 4
  cpu: 32
  seed: 42
  num_modes: 1

gnina_ld_library_path: /mnt/ligandpro/soft/docking/gnina/env/lib/python3.10/site-packages/torch/lib
gnina_container:
  enabled: false
  engine: docker
  image: gnina/gnina:latest
  bin: gnina
  gpus: all
  mounts:
  - /mnt:/mnt
  - /home:/home
  - /tmp:/tmp
