run: true
tools: gnina  # Options: gnina, smina, both
receptor_pdb: data/test/7EW9_apo.pdb
auto_run: true
run_in_background: false
smina_config:
  bin: smina
  autobox_ligand: data/test/05C_from_7EW9.sdf
  autobox_add: 4
  cpu: 32
  seed: 42
  exhaustiveness: 8
  num_modes: 9
gnina_config:
  bin: gnina
  autobox_ligand: data/test/05C_from_7EW9.sdf
  autobox_add: 4
  cpu: 32
  seed: 42

