run: True
batch_size: 512
filter_data: True

borders: 
  allowed_chars: ["C", "N", "S", "O", "F", "Cl", "Br", "H"]

  n_atoms_min: 10
  n_atoms_max: 100

  n_heavy_atoms_min: 10
  n_heavy_atoms_max: 50

  n_N_atoms_min: 0
  n_N_atoms_max: 10

  fN_atoms_min: 0
  fN_atoms_max: 1

  charged_mol_allowed: True 
  filter_charged_mol: False 

  molWt_min: 100
  molWt_max: 1000

  logP_min: -2
  logP_max: 10

  ring_size_min: 3
  ring_size_max: 12

  n_rings_min: 0
  n_rings_max: 6

  n_aroma_rings_min: 0
  n_aroma_rings_max: 5

  n_fused_aromatic_rings_min: 0 
  n_fused_aromatic_rings_max: 2

  n_het_atoms_min: 2
  n_het_atoms_max: 15

  n_rigid_bonds_min: 0
  n_rigid_bonds_max: 30

  n_rot_bonds_min: 2
  n_rot_bonds_max: 8

  hbd_min: 0
  hbd_max: 5.5

  hba_min: 2.5
  hba_max: 12

  fsp3_min: 0.15
  fsp3_max: 0.8

  tpsa_min: 40
  tpsa_max: 140

  qed_min: 0.3
  qed_max: 1

filtered_cols_to_plot: ['chars', 'n_atoms', 'n_heavy_atoms', 'n_N_atoms', 'fN_atoms',
                        'charged_mol', 'molWt', 'logP', 
                        'ring_size', 'n_rings', 'n_aroma_rings', 'n_fused_aromatic_rings', 
                        'n_het_atoms', 'n_rigid_bonds', 'n_rot_bonds', 'hbd', 'hba', 
                        'fsp3', 'tpsa', 'qed']

discrete_features_to_plot: ['chars','charged_mol', 'n_N_atoms',
                            'ring_size', 'n_rings', 'n_aroma_rings', 'n_fused_aromatic_rings', 
                            'n_het_atoms', 'n_rigid_bonds', 'n_rot_bonds', 'hbd', 'hba']

not_to_smooth_plot_by_sides: ['n_atoms', 'n_heavy_atoms', 'fN_atoms',
                              'molWt', 
                              'fsp3', 'tpsa', 'qed',]

                                
renamer: 
  chars: 'Chars in molecules' 
  n_atoms: 'Number of Atoms'
  n_heavy_atoms: 'Number of Heavy Atoms'
  n_N_atoms: 'Number of Nitrogen Atoms'
  fN_atoms: 'Fraction of Nitrogen Atoms'
  charged_mol: 'Charged Molecule'
  molWt: 'Molecular Weight' 
  logP: 'logP' 
  ring_size: 'Size of rings' 
  n_rings: 'Number of rings' 
  n_aroma_rings: 'Number of aromatic rings' 
  n_fused_aromatic_rings: 'Number of fused aromatic rings' 
  n_het_atoms: 'Number of heteroatoms' 
  n_rigid_bonds: 'Number of rigid bonds' 
  n_rot_bonds: 'Number of rotatable bonds' 
  hbd: 'Hydrogen Bond Donors'
  hba: 'Hydrogen Bond Acceptors'
  fsp3: 'Fraction of SP3'
  tpsa: 'TPSA' 
  qed: 'QED'