generated_mols_path: /home/dorochka/other_staff/_data/sampled_smiles/7ew9/*
target_mols_path: data/KRAS_target_mols.csv
folder_to_save: results/7ew9/AllModels/
mode: multi_comparison # single_comparison, multi_comparison


n_jobs: 22
sample_size: 10000
batch_size: 512 
save_sampled_mols: True

pains_file_path: data/wehi_pains.csv
mcf_file_path: data/mcf.csv

config_descriptors: configs/config_descriptors.yml
config_structFilters: configs/config_structFilters.yml
config_molScore: configs/config_molScore.yml
config_retroSynth: configs/config_retroSynth.yml
config_docking: configs/config_docking.yml




