# generated_mols_path: /home/dorochka/projects/testing_benchmark/test_mols.smi
# generated_mols_path: /home/dorochka/data/sampled_smiles/cleanInhibitors/general_generators/only_smiles/reinvent4.csv
generated_mols_path: /home/dorochka/projects/testing_benchmark/test_8mols.smi
target_mols_path: /home/dorochka/data/experiments_input_data/KRAS_ligands/KRAS_first_dataset_prepared_no_dups.csv
# target_mols_path: /home/dorochka/projects/testing_benchmark/KRAS_inhibs_unseen_1.smi
folder_to_save: results/7ew9/MAIN/one_more_run/test

n_jobs: 62
sample_size: 10000
batch_size: 512 
save_sampled_mols: True

pains_file_path: data/wehi_pains.csv
mcf_file_path: data/mcf.csv

config_descriptors: configs/config_descriptors.yml
config_structFilters: configs/config_structFilters.yml
config_retroSynth: configs/config_retroSynth.yml
config_docking: configs/config_docking.yml





